### ISSUE TITLE
GraphqlResponseError (timeout)

### ISSUE THREAD

**Issue by teriu** [advanced-security/sbom-generator-action#4]
I'm getting a

```
GraphqlResponseError: Request failed due to following response errors:
 - timedout
 ```
 
 when I try to run this action.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/4244316/230507688-654d3a46-fe31-407a-960d-1a0273273460.png">

My configuration:

```
name: Dependency Health

on:
  push:
    branches: [main]
  pull_request:

permissions: read-all

jobs:
  licence-checker:
    name: 📑 License Checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # renovate: tag=v3.3.0

      - name: Download Software Bill of Materials (SBOM)
        uses: advanced-security/sbom-generator-action@v0.0.1
        id: sbom
        env:
          GITHUB_TOKEN: ${{ github.token }}

```
